job:
    image: python:3.6
    
    services: 
        - docker:dind

    before_script: 
        - pip install --upgrade pip
        - pip install docker-compose

    script: 
        - service docker start
        - docker-compose run app sh -c 'python manage.py test && flake8'