language: python
python:
    - "3.6"

services:
    - docker

before_script: 
    - pip install docker-compose
    - pip install flake8

script:
    - flake8
    - docker-compose run app sh -c "python manage.py test"